ALTER TABLE comments ADD COLUMN parent_id INTEGER;
ALTER TABLE comments ADD COLUMN status TEXT NOT NULL DEFAULT 'open';
ALTER TABLE comments ADD COLUMN tlo_id INTEGER;
ALTER TABLE comments ADD COLUMN ilo_id INTEGER;
